Update codemender-pr-scan.yml

diff --git a/.github/workflows/codemender-pr-scan.yml b/.github/workflows/codemender-pr-scan.yml
--- a/.github/workflows/codemender-pr-scan.yml
+++ b/.github/workflows/codemender-pr-scan.yml
@@ -87,4 +87,28 @@ jobs:
           for file in "${CHANGED_FILES[@]}"; do
             echo "🔍 Scanning ${{ github.event.pull_request.head.repo.name }}/$file with Gemini 3.7 Flash..."
             cm find "${{ github.event.pull_request.head.repo.name }}/$file" --model gemini-3.7-flash -y 2>&1 | tee scan_output.log
-          done          
+          done
+
+      - name: Report
+        run: |
+          FINDINGS=$(cm report --status OPEN --format json)
+          FINDINGS_COUNT=$(echo "$FINDINGS" | jq '. | length')
+          if [ "$FINDINGS_COUNT" -gt 0 ]; then
+            echo "${FINDINGS_COUNT} findings discovered."
+            echo "## CodeMender Vulnerability Findings Report" >> "$GITHUB_STEP_SUMMARY"
+            cm report -f md >> "$GITHUB_STEP_SUMMARY"
+            exit 1
+          fi
+          
+          echo "No vulnerabilities found!" >> "$GITHUB_STEP_SUMMARY"
+          
+      
+      # Cleanup Sensitive Binaries (Best Practice)
+      - name: Cleanup
+        if: always()
+        run: |
+          rm -f cm-linux-amd64.zip
+          rm -f cm
+          rm -rf .cm_project
+          rm -rf .exploit/
+          rm -f gha-creds-*.json
